x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:
  app:
    image: home-photo-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
      PHOTO_STORAGE_PATH: /app/data
    ports:
      - '8080:8080'
    volumes:
      - ${PHOTO_STORAGE_PATH:?PHOTO_STORAGE_PATH is required}:/app/data
    # user: '0' # root権限で実行
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
